export { default as Home} from './Home/Home'
export { default as Header} from './Header/Header'
export { default as About} from './About/About'
export { default as Cv} from './cv/Cv'
export { default as Resume} from './Resume/Resume'
export { default as Contact} from './Contact/Contact'
export { default as Work} from './Work/Work'
